### ISSUE TITLE
Back arrow in app takes you to a different place than back arrow on device

### ISSUE THREAD

**Issue by dmmortimer** [argilo/BusFollower#13]
Example:
1. Open app, see app home page (form to enter a stop number or name, map button, and list of recent queries).
2. Click Map button.
3. Zoom to area of interest and click on a bus stop flag. Stop summary popup appears.
4. Click Open. Choose a route page appears.
5. Press on a route number. Approaching bus times appear.
6. Decide you want to go back and select a different route.
7. Press the Back arrow in the app (top bar left hand side).
8. Actual behavior: End up on app home page.
9. Expected behavior: Go back to choose a route page.

Workaround: In step 7, use the back button on the device (bottom bar left hand side) instead. This goes back a page.

Maybe it would be useful to have a Home or "start over" button on the app that takes you to the home page instead of to the previous page. But then I wouldn't expect it to be a back arrow.

I'm running version 1.1.11.

**Comment by clayton-shopify** [comment]
Thanks for the report. I'll make sure this gets fixed in version 2.0, which should be out within a week or two.

**Comment by argilo** [comment]
Thanks for the report. I'll make sure this gets fixed in version 2.0, which should be out within a week or two.
