### ISSUE TITLE
Network connection not working

### ISSUE THREAD

**Issue by jen321** [argilo/BusFollower#15]
I really like this app.  I rely on it everyday.

This morning, however, app keeps giving me an error, saying that the network connection is not working.  I don't think it's on my side, but I could be wrong.  Is there something wrong with the server?

**Comment by jen321** [comment]
It's working again!  Thanks!

**Comment by argilo** [comment]
Unfortunately, this sort of issue is almost always out of my control, as the server is operated by OC Transpo. But thanks for reporting the issue, and I'm glad to hear the server was running again soon.
